// Automatically generated by odin 1.2.7 - do not edit
#include <float.h>
#include <R.h>
#include <Rmath.h>
#include <Rinternals.h>
#include <stdbool.h>
#include <R_ext/Rdynload.h>
typedef struct discrete_leloup_goldbeter_noisy_internal {
  double C_ini;
  double C_N_ini;
  double initial_C;
  double initial_C_N;
  double initial_M_P;
  double initial_M_T;
  double initial_P_0;
  double initial_P_1;
  double initial_P_2;
  double initial_T_0;
  double initial_T_1;
  double initial_T_2;
  double k_1;
  double k_2;
  double k_3;
  double k_4;
  double k_d;
  double K_dP;
  double K_dT;
  double K_IP;
  double K_IT;
  double K_mP;
  double K_mT;
  double K_p;
  double k_sP;
  double k_sT;
  double LD_HOURS;
  double M_P_ini;
  double M_T_ini;
  double n;
  double P_0_ini;
  double P_1_ini;
  double P_2_ini;
  double STEP_HOURS;
  double T_0_ini;
  double T_1_ini;
  double T_2_ini;
  double V_1P;
  double V_1T;
  double V_2P;
  double V_2T;
  double V_3P;
  double V_3T;
  double V_4P;
  double V_4T;
  double V_dP;
  double V_mP;
  double V_mT;
  double V_sP;
  double V_sT;
  double VdT_OFF;
  double VdT_ON;
  double VsP_NOISE_RATIO;
  double VsP_NOISE_TYPE;
  double VsT_NOISE_RATIO;
  double VsT_NOISE_TYPE;
} discrete_leloup_goldbeter_noisy_internal;
typedef struct discrete_leloup_goldbeter_internal {
  double C_ini;
  double C_N_ini;
  double initial_C;
  double initial_C_N;
  double initial_M_P;
  double initial_M_T;
  double initial_P_0;
  double initial_P_1;
  double initial_P_2;
  double initial_T_0;
  double initial_T_1;
  double initial_T_2;
  double k_1;
  double k_2;
  double k_3;
  double k_4;
  double k_d;
  double K_dP;
  double K_dT;
  double K_IP;
  double K_IT;
  double K_mP;
  double K_mT;
  double K_p;
  double k_sP;
  double k_sT;
  double LD_HOURS;
  double M_P_ini;
  double M_T_ini;
  double n;
  double P_0_ini;
  double P_1_ini;
  double P_2_ini;
  double STEP_HOURS;
  double T_0_ini;
  double T_1_ini;
  double T_2_ini;
  double V_1P;
  double V_1T;
  double V_2P;
  double V_2T;
  double V_3P;
  double V_3T;
  double V_4P;
  double V_4T;
  double V_dP;
  double V_mP;
  double V_mT;
  double V_sP;
  double V_sT;
  double VdT_OFF;
  double VdT_ON;
} discrete_leloup_goldbeter_internal;
discrete_leloup_goldbeter_noisy_internal* discrete_leloup_goldbeter_noisy_get_internal(SEXP internal_p, int closed_error);
static void discrete_leloup_goldbeter_noisy_finalise(SEXP internal_p);
SEXP discrete_leloup_goldbeter_noisy_create(SEXP user);
void discrete_leloup_goldbeter_noisy_initmod_desolve(void(* odeparms) (int *, double *));
SEXP discrete_leloup_goldbeter_noisy_contents(SEXP internal_p);
SEXP discrete_leloup_goldbeter_noisy_set_user(SEXP internal_p, SEXP user);
SEXP discrete_leloup_goldbeter_noisy_set_initial(SEXP internal_p, SEXP step_ptr, SEXP state_ptr);
SEXP discrete_leloup_goldbeter_noisy_metadata(SEXP internal_p);
SEXP discrete_leloup_goldbeter_noisy_initial_conditions(SEXP internal_p, SEXP step_ptr);
void discrete_leloup_goldbeter_noisy_rhs(discrete_leloup_goldbeter_noisy_internal* internal, size_t step, double * state, double * state_next, double * output);
void discrete_leloup_goldbeter_noisy_rhs_dde(size_t n_eq, size_t step, double * state, double * state_next, size_t n_out, double * output, void * internal);
SEXP discrete_leloup_goldbeter_noisy_rhs_r(SEXP internal_p, SEXP step, SEXP state);
discrete_leloup_goldbeter_internal* discrete_leloup_goldbeter_get_internal(SEXP internal_p, int closed_error);
static void discrete_leloup_goldbeter_finalise(SEXP internal_p);
SEXP discrete_leloup_goldbeter_create(SEXP user);
void discrete_leloup_goldbeter_initmod_desolve(void(* odeparms) (int *, double *));
SEXP discrete_leloup_goldbeter_contents(SEXP internal_p);
SEXP discrete_leloup_goldbeter_set_user(SEXP internal_p, SEXP user);
SEXP discrete_leloup_goldbeter_set_initial(SEXP internal_p, SEXP step_ptr, SEXP state_ptr);
SEXP discrete_leloup_goldbeter_metadata(SEXP internal_p);
SEXP discrete_leloup_goldbeter_initial_conditions(SEXP internal_p, SEXP step_ptr);
void discrete_leloup_goldbeter_rhs(discrete_leloup_goldbeter_internal* internal, size_t step, double * state, double * state_next, double * output);
void discrete_leloup_goldbeter_rhs_dde(size_t n_eq, size_t step, double * state, double * state_next, size_t n_out, double * output, void * internal);
SEXP discrete_leloup_goldbeter_rhs_r(SEXP internal_p, SEXP step, SEXP state);
double user_get_scalar_double(SEXP user, const char *name,
                              double default_value, double min, double max);
int user_get_scalar_int(SEXP user, const char *name,
                        int default_value, double min, double max);
void user_check_values_double(double * value, size_t len,
                                  double min, double max, const char *name);
void user_check_values_int(int * value, size_t len,
                               double min, double max, const char *name);
void user_check_values(SEXP value, double min, double max,
                           const char *name);
SEXP user_list_element(SEXP list, const char *name);
double fmodr(double x, double y);
double fintdiv(double x, double y);
int scalar_int(SEXP x, const char * name);
discrete_leloup_goldbeter_noisy_internal* discrete_leloup_goldbeter_noisy_get_internal(SEXP internal_p, int closed_error) {
  discrete_leloup_goldbeter_noisy_internal *internal = NULL;
  if (TYPEOF(internal_p) != EXTPTRSXP) {
    Rf_error("Expected an external pointer");
  }
  internal = (discrete_leloup_goldbeter_noisy_internal*) R_ExternalPtrAddr(internal_p);
  if (!internal && closed_error) {
    Rf_error("Pointer has been invalidated");
  }
  return internal;
}
void discrete_leloup_goldbeter_noisy_finalise(SEXP internal_p) {
  discrete_leloup_goldbeter_noisy_internal *internal = discrete_leloup_goldbeter_noisy_get_internal(internal_p, 0);
  if (internal_p) {
    R_Free(internal);
    R_ClearExternalPtr(internal_p);
  }
}
SEXP discrete_leloup_goldbeter_noisy_create(SEXP user) {
  discrete_leloup_goldbeter_noisy_internal *internal = (discrete_leloup_goldbeter_noisy_internal*) R_Calloc(1, discrete_leloup_goldbeter_noisy_internal);
  internal->C_ini = 0;
  internal->C_N_ini = 0;
  internal->k_1 = 0.80000000000000004;
  internal->k_2 = 0.20000000000000001;
  internal->k_3 = 1.2;
  internal->k_4 = 0.59999999999999998;
  internal->k_d = 0.01;
  internal->K_dP = 0.20000000000000001;
  internal->K_dT = 0.20000000000000001;
  internal->K_IP = 1;
  internal->K_IT = 1;
  internal->K_mP = 0.20000000000000001;
  internal->K_mT = 0.20000000000000001;
  internal->K_p = 2;
  internal->k_sP = 0.90000000000000002;
  internal->k_sT = 0.90000000000000002;
  internal->LD_HOURS = 120;
  internal->M_P_ini = 0;
  internal->M_T_ini = 0;
  internal->n = 4;
  internal->P_0_ini = 0;
  internal->P_1_ini = 0;
  internal->P_2_ini = 0;
  internal->STEP_HOURS = 0.10000000000000001;
  internal->T_0_ini = 0;
  internal->T_1_ini = 0;
  internal->T_2_ini = 0;
  internal->V_1P = 8;
  internal->V_1T = 8;
  internal->V_2P = 1;
  internal->V_2T = 1;
  internal->V_3P = 8;
  internal->V_3T = 8;
  internal->V_4P = 1;
  internal->V_4T = 1;
  internal->V_dP = 2.2000000000000002;
  internal->V_mP = 1;
  internal->V_mT = 0.69999999999999996;
  internal->V_sP = 1.1000000000000001;
  internal->V_sT = 1;
  internal->VdT_OFF = 3;
  internal->VdT_ON = 6;
  internal->VsP_NOISE_RATIO = -(1);
  internal->VsP_NOISE_TYPE = 0;
  internal->VsT_NOISE_RATIO = -(1);
  internal->VsT_NOISE_TYPE = 0;
  SEXP ptr = PROTECT(R_MakeExternalPtr(internal, R_NilValue, R_NilValue));
  R_RegisterCFinalizer(ptr, discrete_leloup_goldbeter_noisy_finalise);
  UNPROTECT(1);
  return ptr;
}
static discrete_leloup_goldbeter_noisy_internal *discrete_leloup_goldbeter_noisy_internal_ds;
void discrete_leloup_goldbeter_noisy_initmod_desolve(void(* odeparms) (int *, double *)) {
  static DL_FUNC get_desolve_gparms = NULL;
  if (get_desolve_gparms == NULL) {
    get_desolve_gparms =
      R_GetCCallable("deSolve", "get_deSolve_gparms");
  }
  discrete_leloup_goldbeter_noisy_internal_ds = discrete_leloup_goldbeter_noisy_get_internal(get_desolve_gparms(), 1);
}
SEXP discrete_leloup_goldbeter_noisy_contents(SEXP internal_p) {
  discrete_leloup_goldbeter_noisy_internal *internal = discrete_leloup_goldbeter_noisy_get_internal(internal_p, 1);
  SEXP contents = PROTECT(allocVector(VECSXP, 56));
  SET_VECTOR_ELT(contents, 0, ScalarReal(internal->C_ini));
  SET_VECTOR_ELT(contents, 1, ScalarReal(internal->C_N_ini));
  SET_VECTOR_ELT(contents, 2, ScalarReal(internal->initial_C));
  SET_VECTOR_ELT(contents, 3, ScalarReal(internal->initial_C_N));
  SET_VECTOR_ELT(contents, 4, ScalarReal(internal->initial_M_P));
  SET_VECTOR_ELT(contents, 5, ScalarReal(internal->initial_M_T));
  SET_VECTOR_ELT(contents, 6, ScalarReal(internal->initial_P_0));
  SET_VECTOR_ELT(contents, 7, ScalarReal(internal->initial_P_1));
  SET_VECTOR_ELT(contents, 8, ScalarReal(internal->initial_P_2));
  SET_VECTOR_ELT(contents, 9, ScalarReal(internal->initial_T_0));
  SET_VECTOR_ELT(contents, 10, ScalarReal(internal->initial_T_1));
  SET_VECTOR_ELT(contents, 11, ScalarReal(internal->initial_T_2));
  SET_VECTOR_ELT(contents, 12, ScalarReal(internal->k_1));
  SET_VECTOR_ELT(contents, 13, ScalarReal(internal->k_2));
  SET_VECTOR_ELT(contents, 14, ScalarReal(internal->k_3));
  SET_VECTOR_ELT(contents, 15, ScalarReal(internal->k_4));
  SET_VECTOR_ELT(contents, 16, ScalarReal(internal->k_d));
  SET_VECTOR_ELT(contents, 17, ScalarReal(internal->K_dP));
  SET_VECTOR_ELT(contents, 18, ScalarReal(internal->K_dT));
  SET_VECTOR_ELT(contents, 19, ScalarReal(internal->K_IP));
  SET_VECTOR_ELT(contents, 20, ScalarReal(internal->K_IT));
  SET_VECTOR_ELT(contents, 21, ScalarReal(internal->K_mP));
  SET_VECTOR_ELT(contents, 22, ScalarReal(internal->K_mT));
  SET_VECTOR_ELT(contents, 23, ScalarReal(internal->K_p));
  SET_VECTOR_ELT(contents, 24, ScalarReal(internal->k_sP));
  SET_VECTOR_ELT(contents, 25, ScalarReal(internal->k_sT));
  SET_VECTOR_ELT(contents, 26, ScalarReal(internal->LD_HOURS));
  SET_VECTOR_ELT(contents, 27, ScalarReal(internal->M_P_ini));
  SET_VECTOR_ELT(contents, 28, ScalarReal(internal->M_T_ini));
  SET_VECTOR_ELT(contents, 29, ScalarReal(internal->n));
  SET_VECTOR_ELT(contents, 30, ScalarReal(internal->P_0_ini));
  SET_VECTOR_ELT(contents, 31, ScalarReal(internal->P_1_ini));
  SET_VECTOR_ELT(contents, 32, ScalarReal(internal->P_2_ini));
  SET_VECTOR_ELT(contents, 33, ScalarReal(internal->STEP_HOURS));
  SET_VECTOR_ELT(contents, 34, ScalarReal(internal->T_0_ini));
  SET_VECTOR_ELT(contents, 35, ScalarReal(internal->T_1_ini));
  SET_VECTOR_ELT(contents, 36, ScalarReal(internal->T_2_ini));
  SET_VECTOR_ELT(contents, 37, ScalarReal(internal->V_1P));
  SET_VECTOR_ELT(contents, 38, ScalarReal(internal->V_1T));
  SET_VECTOR_ELT(contents, 39, ScalarReal(internal->V_2P));
  SET_VECTOR_ELT(contents, 40, ScalarReal(internal->V_2T));
  SET_VECTOR_ELT(contents, 41, ScalarReal(internal->V_3P));
  SET_VECTOR_ELT(contents, 42, ScalarReal(internal->V_3T));
  SET_VECTOR_ELT(contents, 43, ScalarReal(internal->V_4P));
  SET_VECTOR_ELT(contents, 44, ScalarReal(internal->V_4T));
  SET_VECTOR_ELT(contents, 45, ScalarReal(internal->V_dP));
  SET_VECTOR_ELT(contents, 46, ScalarReal(internal->V_mP));
  SET_VECTOR_ELT(contents, 47, ScalarReal(internal->V_mT));
  SET_VECTOR_ELT(contents, 48, ScalarReal(internal->V_sP));
  SET_VECTOR_ELT(contents, 49, ScalarReal(internal->V_sT));
  SET_VECTOR_ELT(contents, 50, ScalarReal(internal->VdT_OFF));
  SET_VECTOR_ELT(contents, 51, ScalarReal(internal->VdT_ON));
  SET_VECTOR_ELT(contents, 52, ScalarReal(internal->VsP_NOISE_RATIO));
  SET_VECTOR_ELT(contents, 53, ScalarReal(internal->VsP_NOISE_TYPE));
  SET_VECTOR_ELT(contents, 54, ScalarReal(internal->VsT_NOISE_RATIO));
  SET_VECTOR_ELT(contents, 55, ScalarReal(internal->VsT_NOISE_TYPE));
  SEXP nms = PROTECT(allocVector(STRSXP, 56));
  SET_STRING_ELT(nms, 0, mkChar("C_ini"));
  SET_STRING_ELT(nms, 1, mkChar("C_N_ini"));
  SET_STRING_ELT(nms, 2, mkChar("initial_C"));
  SET_STRING_ELT(nms, 3, mkChar("initial_C_N"));
  SET_STRING_ELT(nms, 4, mkChar("initial_M_P"));
  SET_STRING_ELT(nms, 5, mkChar("initial_M_T"));
  SET_STRING_ELT(nms, 6, mkChar("initial_P_0"));
  SET_STRING_ELT(nms, 7, mkChar("initial_P_1"));
  SET_STRING_ELT(nms, 8, mkChar("initial_P_2"));
  SET_STRING_ELT(nms, 9, mkChar("initial_T_0"));
  SET_STRING_ELT(nms, 10, mkChar("initial_T_1"));
  SET_STRING_ELT(nms, 11, mkChar("initial_T_2"));
  SET_STRING_ELT(nms, 12, mkChar("k_1"));
  SET_STRING_ELT(nms, 13, mkChar("k_2"));
  SET_STRING_ELT(nms, 14, mkChar("k_3"));
  SET_STRING_ELT(nms, 15, mkChar("k_4"));
  SET_STRING_ELT(nms, 16, mkChar("k_d"));
  SET_STRING_ELT(nms, 17, mkChar("K_dP"));
  SET_STRING_ELT(nms, 18, mkChar("K_dT"));
  SET_STRING_ELT(nms, 19, mkChar("K_IP"));
  SET_STRING_ELT(nms, 20, mkChar("K_IT"));
  SET_STRING_ELT(nms, 21, mkChar("K_mP"));
  SET_STRING_ELT(nms, 22, mkChar("K_mT"));
  SET_STRING_ELT(nms, 23, mkChar("K_p"));
  SET_STRING_ELT(nms, 24, mkChar("k_sP"));
  SET_STRING_ELT(nms, 25, mkChar("k_sT"));
  SET_STRING_ELT(nms, 26, mkChar("LD_HOURS"));
  SET_STRING_ELT(nms, 27, mkChar("M_P_ini"));
  SET_STRING_ELT(nms, 28, mkChar("M_T_ini"));
  SET_STRING_ELT(nms, 29, mkChar("n"));
  SET_STRING_ELT(nms, 30, mkChar("P_0_ini"));
  SET_STRING_ELT(nms, 31, mkChar("P_1_ini"));
  SET_STRING_ELT(nms, 32, mkChar("P_2_ini"));
  SET_STRING_ELT(nms, 33, mkChar("STEP_HOURS"));
  SET_STRING_ELT(nms, 34, mkChar("T_0_ini"));
  SET_STRING_ELT(nms, 35, mkChar("T_1_ini"));
  SET_STRING_ELT(nms, 36, mkChar("T_2_ini"));
  SET_STRING_ELT(nms, 37, mkChar("V_1P"));
  SET_STRING_ELT(nms, 38, mkChar("V_1T"));
  SET_STRING_ELT(nms, 39, mkChar("V_2P"));
  SET_STRING_ELT(nms, 40, mkChar("V_2T"));
  SET_STRING_ELT(nms, 41, mkChar("V_3P"));
  SET_STRING_ELT(nms, 42, mkChar("V_3T"));
  SET_STRING_ELT(nms, 43, mkChar("V_4P"));
  SET_STRING_ELT(nms, 44, mkChar("V_4T"));
  SET_STRING_ELT(nms, 45, mkChar("V_dP"));
  SET_STRING_ELT(nms, 46, mkChar("V_mP"));
  SET_STRING_ELT(nms, 47, mkChar("V_mT"));
  SET_STRING_ELT(nms, 48, mkChar("V_sP"));
  SET_STRING_ELT(nms, 49, mkChar("V_sT"));
  SET_STRING_ELT(nms, 50, mkChar("VdT_OFF"));
  SET_STRING_ELT(nms, 51, mkChar("VdT_ON"));
  SET_STRING_ELT(nms, 52, mkChar("VsP_NOISE_RATIO"));
  SET_STRING_ELT(nms, 53, mkChar("VsP_NOISE_TYPE"));
  SET_STRING_ELT(nms, 54, mkChar("VsT_NOISE_RATIO"));
  SET_STRING_ELT(nms, 55, mkChar("VsT_NOISE_TYPE"));
  setAttrib(contents, R_NamesSymbol, nms);
  UNPROTECT(2);
  return contents;
}
SEXP discrete_leloup_goldbeter_noisy_set_user(SEXP internal_p, SEXP user) {
  discrete_leloup_goldbeter_noisy_internal *internal = discrete_leloup_goldbeter_noisy_get_internal(internal_p, 1);
  internal->C_ini = user_get_scalar_double(user, "C_ini", internal->C_ini, NA_REAL, NA_REAL);
  internal->C_N_ini = user_get_scalar_double(user, "C_N_ini", internal->C_N_ini, NA_REAL, NA_REAL);
  internal->k_1 = user_get_scalar_double(user, "k_1", internal->k_1, NA_REAL, NA_REAL);
  internal->k_2 = user_get_scalar_double(user, "k_2", internal->k_2, NA_REAL, NA_REAL);
  internal->k_3 = user_get_scalar_double(user, "k_3", internal->k_3, NA_REAL, NA_REAL);
  internal->k_4 = user_get_scalar_double(user, "k_4", internal->k_4, NA_REAL, NA_REAL);
  internal->k_d = user_get_scalar_double(user, "k_d", internal->k_d, NA_REAL, NA_REAL);
  internal->K_dP = user_get_scalar_double(user, "K_dP", internal->K_dP, NA_REAL, NA_REAL);
  internal->K_dT = user_get_scalar_double(user, "K_dT", internal->K_dT, NA_REAL, NA_REAL);
  internal->K_IP = user_get_scalar_double(user, "K_IP", internal->K_IP, NA_REAL, NA_REAL);
  internal->K_IT = user_get_scalar_double(user, "K_IT", internal->K_IT, NA_REAL, NA_REAL);
  internal->K_mP = user_get_scalar_double(user, "K_mP", internal->K_mP, NA_REAL, NA_REAL);
  internal->K_mT = user_get_scalar_double(user, "K_mT", internal->K_mT, NA_REAL, NA_REAL);
  internal->K_p = user_get_scalar_double(user, "K_p", internal->K_p, NA_REAL, NA_REAL);
  internal->k_sP = user_get_scalar_double(user, "k_sP", internal->k_sP, NA_REAL, NA_REAL);
  internal->k_sT = user_get_scalar_double(user, "k_sT", internal->k_sT, NA_REAL, NA_REAL);
  internal->LD_HOURS = user_get_scalar_double(user, "LD_HOURS", internal->LD_HOURS, NA_REAL, NA_REAL);
  internal->M_P_ini = user_get_scalar_double(user, "M_P_ini", internal->M_P_ini, NA_REAL, NA_REAL);
  internal->M_T_ini = user_get_scalar_double(user, "M_T_ini", internal->M_T_ini, NA_REAL, NA_REAL);
  internal->n = user_get_scalar_double(user, "n", internal->n, NA_REAL, NA_REAL);
  internal->P_0_ini = user_get_scalar_double(user, "P_0_ini", internal->P_0_ini, NA_REAL, NA_REAL);
  internal->P_1_ini = user_get_scalar_double(user, "P_1_ini", internal->P_1_ini, NA_REAL, NA_REAL);
  internal->P_2_ini = user_get_scalar_double(user, "P_2_ini", internal->P_2_ini, NA_REAL, NA_REAL);
  internal->STEP_HOURS = user_get_scalar_double(user, "STEP_HOURS", internal->STEP_HOURS, NA_REAL, NA_REAL);
  internal->T_0_ini = user_get_scalar_double(user, "T_0_ini", internal->T_0_ini, NA_REAL, NA_REAL);
  internal->T_1_ini = user_get_scalar_double(user, "T_1_ini", internal->T_1_ini, NA_REAL, NA_REAL);
  internal->T_2_ini = user_get_scalar_double(user, "T_2_ini", internal->T_2_ini, NA_REAL, NA_REAL);
  internal->V_1P = user_get_scalar_double(user, "V_1P", internal->V_1P, NA_REAL, NA_REAL);
  internal->V_1T = user_get_scalar_double(user, "V_1T", internal->V_1T, NA_REAL, NA_REAL);
  internal->V_2P = user_get_scalar_double(user, "V_2P", internal->V_2P, NA_REAL, NA_REAL);
  internal->V_2T = user_get_scalar_double(user, "V_2T", internal->V_2T, NA_REAL, NA_REAL);
  internal->V_3P = user_get_scalar_double(user, "V_3P", internal->V_3P, NA_REAL, NA_REAL);
  internal->V_3T = user_get_scalar_double(user, "V_3T", internal->V_3T, NA_REAL, NA_REAL);
  internal->V_4P = user_get_scalar_double(user, "V_4P", internal->V_4P, NA_REAL, NA_REAL);
  internal->V_4T = user_get_scalar_double(user, "V_4T", internal->V_4T, NA_REAL, NA_REAL);
  internal->V_dP = user_get_scalar_double(user, "V_dP", internal->V_dP, NA_REAL, NA_REAL);
  internal->V_mP = user_get_scalar_double(user, "V_mP", internal->V_mP, NA_REAL, NA_REAL);
  internal->V_mT = user_get_scalar_double(user, "V_mT", internal->V_mT, NA_REAL, NA_REAL);
  internal->V_sP = user_get_scalar_double(user, "V_sP", internal->V_sP, NA_REAL, NA_REAL);
  internal->V_sT = user_get_scalar_double(user, "V_sT", internal->V_sT, NA_REAL, NA_REAL);
  internal->VdT_OFF = user_get_scalar_double(user, "VdT_OFF", internal->VdT_OFF, NA_REAL, NA_REAL);
  internal->VdT_ON = user_get_scalar_double(user, "VdT_ON", internal->VdT_ON, NA_REAL, NA_REAL);
  internal->VsP_NOISE_RATIO = user_get_scalar_double(user, "VsP_NOISE_RATIO", internal->VsP_NOISE_RATIO, NA_REAL, NA_REAL);
  internal->VsP_NOISE_TYPE = user_get_scalar_double(user, "VsP_NOISE_TYPE", internal->VsP_NOISE_TYPE, NA_REAL, NA_REAL);
  internal->VsT_NOISE_RATIO = user_get_scalar_double(user, "VsT_NOISE_RATIO", internal->VsT_NOISE_RATIO, NA_REAL, NA_REAL);
  internal->VsT_NOISE_TYPE = user_get_scalar_double(user, "VsT_NOISE_TYPE", internal->VsT_NOISE_TYPE, NA_REAL, NA_REAL);
  internal->initial_C = internal->C_ini;
  internal->initial_C_N = internal->C_N_ini;
  internal->initial_M_P = internal->M_P_ini;
  internal->initial_M_T = internal->M_T_ini;
  internal->initial_P_0 = internal->P_0_ini;
  internal->initial_P_1 = internal->P_1_ini;
  internal->initial_P_2 = internal->P_2_ini;
  internal->initial_T_0 = internal->T_0_ini;
  internal->initial_T_1 = internal->T_1_ini;
  internal->initial_T_2 = internal->T_2_ini;
  return R_NilValue;
}
SEXP discrete_leloup_goldbeter_noisy_set_initial(SEXP internal_p, SEXP step_ptr, SEXP state_ptr) {
  return R_NilValue;
}
SEXP discrete_leloup_goldbeter_noisy_metadata(SEXP internal_p) {
  discrete_leloup_goldbeter_noisy_internal *internal = discrete_leloup_goldbeter_noisy_get_internal(internal_p, 1);
  SEXP ret = PROTECT(allocVector(VECSXP, 4));
  SEXP nms = PROTECT(allocVector(STRSXP, 4));
  SET_STRING_ELT(nms, 0, mkChar("variable_order"));
  SET_STRING_ELT(nms, 1, mkChar("output_order"));
  SET_STRING_ELT(nms, 2, mkChar("n_out"));
  SET_STRING_ELT(nms, 3, mkChar("interpolate_t"));
  setAttrib(ret, R_NamesSymbol, nms);
  SEXP variable_length = PROTECT(allocVector(VECSXP, 10));
  SEXP variable_names = PROTECT(allocVector(STRSXP, 10));
  setAttrib(variable_length, R_NamesSymbol, variable_names);
  SET_VECTOR_ELT(variable_length, 0, R_NilValue);
  SET_VECTOR_ELT(variable_length, 1, R_NilValue);
  SET_VECTOR_ELT(variable_length, 2, R_NilValue);
  SET_VECTOR_ELT(variable_length, 3, R_NilValue);
  SET_VECTOR_ELT(variable_length, 4, R_NilValue);
  SET_VECTOR_ELT(variable_length, 5, R_NilValue);
  SET_VECTOR_ELT(variable_length, 6, R_NilValue);
  SET_VECTOR_ELT(variable_length, 7, R_NilValue);
  SET_VECTOR_ELT(variable_length, 8, R_NilValue);
  SET_VECTOR_ELT(variable_length, 9, R_NilValue);
  SET_STRING_ELT(variable_names, 0, mkChar("M_T"));
  SET_STRING_ELT(variable_names, 1, mkChar("M_P"));
  SET_STRING_ELT(variable_names, 2, mkChar("T_0"));
  SET_STRING_ELT(variable_names, 3, mkChar("T_1"));
  SET_STRING_ELT(variable_names, 4, mkChar("T_2"));
  SET_STRING_ELT(variable_names, 5, mkChar("P_0"));
  SET_STRING_ELT(variable_names, 6, mkChar("P_1"));
  SET_STRING_ELT(variable_names, 7, mkChar("P_2"));
  SET_STRING_ELT(variable_names, 8, mkChar("C"));
  SET_STRING_ELT(variable_names, 9, mkChar("C_N"));
  SET_VECTOR_ELT(ret, 0, variable_length);
  UNPROTECT(2);
  SET_VECTOR_ELT(ret, 1, R_NilValue);
  SET_VECTOR_ELT(ret, 2, ScalarInteger(0));
  UNPROTECT(2);
  return ret;
}
SEXP discrete_leloup_goldbeter_noisy_initial_conditions(SEXP internal_p, SEXP step_ptr) {
  discrete_leloup_goldbeter_noisy_internal *internal = discrete_leloup_goldbeter_noisy_get_internal(internal_p, 1);
  SEXP r_state = PROTECT(allocVector(REALSXP, 10));
  double * state = REAL(r_state);
  state[0] = internal->initial_M_T;
  state[1] = internal->initial_M_P;
  state[2] = internal->initial_T_0;
  state[3] = internal->initial_T_1;
  state[4] = internal->initial_T_2;
  state[5] = internal->initial_P_0;
  state[6] = internal->initial_P_1;
  state[7] = internal->initial_P_2;
  state[8] = internal->initial_C;
  state[9] = internal->initial_C_N;
  UNPROTECT(1);
  return r_state;
}
void discrete_leloup_goldbeter_noisy_rhs(discrete_leloup_goldbeter_noisy_internal* internal, size_t step, double * state, double * state_next, double * output) {
  double M_T = state[0];
  double M_P = state[1];
  double T_0 = state[2];
  double T_1 = state[3];
  double T_2 = state[4];
  double P_0 = state[5];
  double P_1 = state[6];
  double P_2 = state[7];
  double C = state[8];
  double C_N = state[9];
  double current_hour = step * internal->STEP_HOURS;
  double inc_hour10 = internal->k_1 * C - internal->k_2 * C_N - internal->k_d * C_N;
  double inc_hour3 = internal->k_sT * M_T + internal->V_2T * T_1 / (double) (internal->K_p + T_1) - internal->k_d * T_0 - internal->V_1T * T_0 / (double) (internal->K_p + T_0);
  double inc_hour4 = internal->V_1T * T_0 / (double) (internal->K_p + T_0) + internal->V_4T * T_2 / (double) (internal->K_p + T_2) - internal->k_d * T_1 - internal->V_2T * T_1 / (double) (internal->K_p + T_1) - internal->V_3T * T_1 / (double) (internal->K_p + T_1);
  double inc_hour6 = internal->k_sP * M_P + internal->V_2P * P_1 / (double) (internal->K_p + P_1) - internal->k_d * P_0 - internal->V_1P * P_0 / (double) (internal->K_p + P_0);
  double inc_hour7 = internal->V_1P * P_0 / (double) (internal->K_p + P_0) + internal->V_4P * P_2 / (double) (internal->K_p + P_2) - internal->k_d * P_1 - internal->V_2P * P_1 / (double) (internal->K_p + P_1) - internal->V_3P * P_1 / (double) (internal->K_p + P_1);
  double inc_hour8 = internal->V_3P * P_1 / (double) (internal->K_p + P_1) + internal->k_4 * C - internal->k_d * P_2 - internal->k_3 * P_2 * P_2 - internal->V_4P * P_2 / (double) (internal->K_p + P_2) - internal->V_dP * P_2 / (double) (internal->K_dP + P_2);
  double inc_hour9 = internal->k_3 * P_2 * T_2 + internal->k_2 * C_N - (internal->k_4 * C + internal->k_1 * C + internal->k_d * C);
  double noise1 = (internal->VsT_NOISE_RATIO > 0 && internal->VsT_NOISE_TYPE == 0 ? fmin(1, fmax(-(1), Rf_rnorm(0, internal->VsT_NOISE_RATIO))) : (internal->VsT_NOISE_RATIO > 0 ? (Rf_runif(-(internal->VsT_NOISE_RATIO), internal->VsT_NOISE_RATIO)) : 0));
  double noise2 = (internal->VsP_NOISE_RATIO > 0 && internal->VsP_NOISE_TYPE == 0 ? fmin(1, fmax(-(1), Rf_rnorm(0, internal->VsP_NOISE_RATIO))) : (internal->VsP_NOISE_RATIO > 0 ? (Rf_runif(-(internal->VsP_NOISE_RATIO), internal->VsP_NOISE_RATIO)) : 0));
  state_next[8] = C + inc_hour9 * internal->STEP_HOURS;
  state_next[9] = C_N + inc_hour10 * internal->STEP_HOURS;
  state_next[5] = P_0 + inc_hour6 * internal->STEP_HOURS;
  state_next[6] = P_1 + inc_hour7 * internal->STEP_HOURS;
  state_next[7] = P_2 + inc_hour8 * internal->STEP_HOURS;
  state_next[2] = T_0 + inc_hour3 * internal->STEP_HOURS;
  state_next[3] = T_1 + inc_hour4 * internal->STEP_HOURS;
  double V_dT = (current_hour <= internal->LD_HOURS && (fmodr((fintdiv(current_hour, 12)), 2) == 1) ? internal->VdT_ON : internal->VdT_OFF);
  double V_sP_noise = internal->V_sP * (1 + noise2);
  double V_sT_noise = internal->V_sT * (1 + noise1);
  double inc_hour1 = V_sT_noise * pow(internal->K_IT, internal->n) / (double) (pow(internal->K_IT, internal->n) + pow(C_N, internal->n)) - internal->k_d * M_T - internal->V_mT * M_T / (double) (internal->K_mT + M_T);
  double inc_hour2 = V_sP_noise * pow(internal->K_IP, internal->n) / (double) (pow(internal->K_IP, internal->n) + pow(C_N, internal->n)) - internal->k_d * M_P - internal->V_mP * M_P / (double) (internal->K_mP + M_P);
  double inc_hour5 = internal->V_3T * T_1 / (double) (internal->K_p + T_1) + internal->k_4 * C - internal->k_d * T_2 - internal->k_3 * P_2 * T_2 - internal->V_4T * T_2 / (double) (internal->K_p + T_2) - V_dT * T_2 / (double) (internal->K_dT + T_2);
  state_next[1] = M_P + inc_hour2 * internal->STEP_HOURS;
  state_next[0] = M_T + inc_hour1 * internal->STEP_HOURS;
  state_next[4] = T_2 + inc_hour5 * internal->STEP_HOURS;
}
void discrete_leloup_goldbeter_noisy_rhs_dde(size_t n_eq, size_t step, double * state, double * state_next, size_t n_out, double * output, void * internal) {
  discrete_leloup_goldbeter_noisy_rhs((discrete_leloup_goldbeter_noisy_internal*)internal, step, state, state_next, output);
}
SEXP discrete_leloup_goldbeter_noisy_rhs_r(SEXP internal_p, SEXP step, SEXP state) {
  SEXP state_next = PROTECT(allocVector(REALSXP, LENGTH(state)));
  discrete_leloup_goldbeter_noisy_internal *internal = discrete_leloup_goldbeter_noisy_get_internal(internal_p, 1);
  double *output = NULL;
  GetRNGstate();
  discrete_leloup_goldbeter_noisy_rhs(internal, scalar_int(step, "step"), REAL(state), REAL(state_next), output);
  PutRNGstate();
  UNPROTECT(1);
  return state_next;
}
discrete_leloup_goldbeter_internal* discrete_leloup_goldbeter_get_internal(SEXP internal_p, int closed_error) {
  discrete_leloup_goldbeter_internal *internal = NULL;
  if (TYPEOF(internal_p) != EXTPTRSXP) {
    Rf_error("Expected an external pointer");
  }
  internal = (discrete_leloup_goldbeter_internal*) R_ExternalPtrAddr(internal_p);
  if (!internal && closed_error) {
    Rf_error("Pointer has been invalidated");
  }
  return internal;
}
void discrete_leloup_goldbeter_finalise(SEXP internal_p) {
  discrete_leloup_goldbeter_internal *internal = discrete_leloup_goldbeter_get_internal(internal_p, 0);
  if (internal_p) {
    R_Free(internal);
    R_ClearExternalPtr(internal_p);
  }
}
SEXP discrete_leloup_goldbeter_create(SEXP user) {
  discrete_leloup_goldbeter_internal *internal = (discrete_leloup_goldbeter_internal*) R_Calloc(1, discrete_leloup_goldbeter_internal);
  internal->C_ini = 0;
  internal->C_N_ini = 0;
  internal->k_1 = 0.80000000000000004;
  internal->k_2 = 0.20000000000000001;
  internal->k_3 = 1.2;
  internal->k_4 = 0.59999999999999998;
  internal->k_d = 0.01;
  internal->K_dP = 0.20000000000000001;
  internal->K_dT = 0.20000000000000001;
  internal->K_IP = 1;
  internal->K_IT = 1;
  internal->K_mP = 0.20000000000000001;
  internal->K_mT = 0.20000000000000001;
  internal->K_p = 2;
  internal->k_sP = 0.90000000000000002;
  internal->k_sT = 0.90000000000000002;
  internal->LD_HOURS = 120;
  internal->M_P_ini = 0;
  internal->M_T_ini = 0;
  internal->n = 4;
  internal->P_0_ini = 0;
  internal->P_1_ini = 0;
  internal->P_2_ini = 0;
  internal->STEP_HOURS = 0.10000000000000001;
  internal->T_0_ini = 0;
  internal->T_1_ini = 0;
  internal->T_2_ini = 0;
  internal->V_1P = 8;
  internal->V_1T = 8;
  internal->V_2P = 1;
  internal->V_2T = 1;
  internal->V_3P = 8;
  internal->V_3T = 8;
  internal->V_4P = 1;
  internal->V_4T = 1;
  internal->V_dP = 2.2000000000000002;
  internal->V_mP = 1;
  internal->V_mT = 0.69999999999999996;
  internal->V_sP = 1.1000000000000001;
  internal->V_sT = 1;
  internal->VdT_OFF = 3;
  internal->VdT_ON = 6;
  SEXP ptr = PROTECT(R_MakeExternalPtr(internal, R_NilValue, R_NilValue));
  R_RegisterCFinalizer(ptr, discrete_leloup_goldbeter_finalise);
  UNPROTECT(1);
  return ptr;
}
static discrete_leloup_goldbeter_internal *discrete_leloup_goldbeter_internal_ds;
void discrete_leloup_goldbeter_initmod_desolve(void(* odeparms) (int *, double *)) {
  static DL_FUNC get_desolve_gparms = NULL;
  if (get_desolve_gparms == NULL) {
    get_desolve_gparms =
      R_GetCCallable("deSolve", "get_deSolve_gparms");
  }
  discrete_leloup_goldbeter_internal_ds = discrete_leloup_goldbeter_get_internal(get_desolve_gparms(), 1);
}
SEXP discrete_leloup_goldbeter_contents(SEXP internal_p) {
  discrete_leloup_goldbeter_internal *internal = discrete_leloup_goldbeter_get_internal(internal_p, 1);
  SEXP contents = PROTECT(allocVector(VECSXP, 52));
  SET_VECTOR_ELT(contents, 0, ScalarReal(internal->C_ini));
  SET_VECTOR_ELT(contents, 1, ScalarReal(internal->C_N_ini));
  SET_VECTOR_ELT(contents, 2, ScalarReal(internal->initial_C));
  SET_VECTOR_ELT(contents, 3, ScalarReal(internal->initial_C_N));
  SET_VECTOR_ELT(contents, 4, ScalarReal(internal->initial_M_P));
  SET_VECTOR_ELT(contents, 5, ScalarReal(internal->initial_M_T));
  SET_VECTOR_ELT(contents, 6, ScalarReal(internal->initial_P_0));
  SET_VECTOR_ELT(contents, 7, ScalarReal(internal->initial_P_1));
  SET_VECTOR_ELT(contents, 8, ScalarReal(internal->initial_P_2));
  SET_VECTOR_ELT(contents, 9, ScalarReal(internal->initial_T_0));
  SET_VECTOR_ELT(contents, 10, ScalarReal(internal->initial_T_1));
  SET_VECTOR_ELT(contents, 11, ScalarReal(internal->initial_T_2));
  SET_VECTOR_ELT(contents, 12, ScalarReal(internal->k_1));
  SET_VECTOR_ELT(contents, 13, ScalarReal(internal->k_2));
  SET_VECTOR_ELT(contents, 14, ScalarReal(internal->k_3));
  SET_VECTOR_ELT(contents, 15, ScalarReal(internal->k_4));
  SET_VECTOR_ELT(contents, 16, ScalarReal(internal->k_d));
  SET_VECTOR_ELT(contents, 17, ScalarReal(internal->K_dP));
  SET_VECTOR_ELT(contents, 18, ScalarReal(internal->K_dT));
  SET_VECTOR_ELT(contents, 19, ScalarReal(internal->K_IP));
  SET_VECTOR_ELT(contents, 20, ScalarReal(internal->K_IT));
  SET_VECTOR_ELT(contents, 21, ScalarReal(internal->K_mP));
  SET_VECTOR_ELT(contents, 22, ScalarReal(internal->K_mT));
  SET_VECTOR_ELT(contents, 23, ScalarReal(internal->K_p));
  SET_VECTOR_ELT(contents, 24, ScalarReal(internal->k_sP));
  SET_VECTOR_ELT(contents, 25, ScalarReal(internal->k_sT));
  SET_VECTOR_ELT(contents, 26, ScalarReal(internal->LD_HOURS));
  SET_VECTOR_ELT(contents, 27, ScalarReal(internal->M_P_ini));
  SET_VECTOR_ELT(contents, 28, ScalarReal(internal->M_T_ini));
  SET_VECTOR_ELT(contents, 29, ScalarReal(internal->n));
  SET_VECTOR_ELT(contents, 30, ScalarReal(internal->P_0_ini));
  SET_VECTOR_ELT(contents, 31, ScalarReal(internal->P_1_ini));
  SET_VECTOR_ELT(contents, 32, ScalarReal(internal->P_2_ini));
  SET_VECTOR_ELT(contents, 33, ScalarReal(internal->STEP_HOURS));
  SET_VECTOR_ELT(contents, 34, ScalarReal(internal->T_0_ini));
  SET_VECTOR_ELT(contents, 35, ScalarReal(internal->T_1_ini));
  SET_VECTOR_ELT(contents, 36, ScalarReal(internal->T_2_ini));
  SET_VECTOR_ELT(contents, 37, ScalarReal(internal->V_1P));
  SET_VECTOR_ELT(contents, 38, ScalarReal(internal->V_1T));
  SET_VECTOR_ELT(contents, 39, ScalarReal(internal->V_2P));
  SET_VECTOR_ELT(contents, 40, ScalarReal(internal->V_2T));
  SET_VECTOR_ELT(contents, 41, ScalarReal(internal->V_3P));
  SET_VECTOR_ELT(contents, 42, ScalarReal(internal->V_3T));
  SET_VECTOR_ELT(contents, 43, ScalarReal(internal->V_4P));
  SET_VECTOR_ELT(contents, 44, ScalarReal(internal->V_4T));
  SET_VECTOR_ELT(contents, 45, ScalarReal(internal->V_dP));
  SET_VECTOR_ELT(contents, 46, ScalarReal(internal->V_mP));
  SET_VECTOR_ELT(contents, 47, ScalarReal(internal->V_mT));
  SET_VECTOR_ELT(contents, 48, ScalarReal(internal->V_sP));
  SET_VECTOR_ELT(contents, 49, ScalarReal(internal->V_sT));
  SET_VECTOR_ELT(contents, 50, ScalarReal(internal->VdT_OFF));
  SET_VECTOR_ELT(contents, 51, ScalarReal(internal->VdT_ON));
  SEXP nms = PROTECT(allocVector(STRSXP, 52));
  SET_STRING_ELT(nms, 0, mkChar("C_ini"));
  SET_STRING_ELT(nms, 1, mkChar("C_N_ini"));
  SET_STRING_ELT(nms, 2, mkChar("initial_C"));
  SET_STRING_ELT(nms, 3, mkChar("initial_C_N"));
  SET_STRING_ELT(nms, 4, mkChar("initial_M_P"));
  SET_STRING_ELT(nms, 5, mkChar("initial_M_T"));
  SET_STRING_ELT(nms, 6, mkChar("initial_P_0"));
  SET_STRING_ELT(nms, 7, mkChar("initial_P_1"));
  SET_STRING_ELT(nms, 8, mkChar("initial_P_2"));
  SET_STRING_ELT(nms, 9, mkChar("initial_T_0"));
  SET_STRING_ELT(nms, 10, mkChar("initial_T_1"));
  SET_STRING_ELT(nms, 11, mkChar("initial_T_2"));
  SET_STRING_ELT(nms, 12, mkChar("k_1"));
  SET_STRING_ELT(nms, 13, mkChar("k_2"));
  SET_STRING_ELT(nms, 14, mkChar("k_3"));
  SET_STRING_ELT(nms, 15, mkChar("k_4"));
  SET_STRING_ELT(nms, 16, mkChar("k_d"));
  SET_STRING_ELT(nms, 17, mkChar("K_dP"));
  SET_STRING_ELT(nms, 18, mkChar("K_dT"));
  SET_STRING_ELT(nms, 19, mkChar("K_IP"));
  SET_STRING_ELT(nms, 20, mkChar("K_IT"));
  SET_STRING_ELT(nms, 21, mkChar("K_mP"));
  SET_STRING_ELT(nms, 22, mkChar("K_mT"));
  SET_STRING_ELT(nms, 23, mkChar("K_p"));
  SET_STRING_ELT(nms, 24, mkChar("k_sP"));
  SET_STRING_ELT(nms, 25, mkChar("k_sT"));
  SET_STRING_ELT(nms, 26, mkChar("LD_HOURS"));
  SET_STRING_ELT(nms, 27, mkChar("M_P_ini"));
  SET_STRING_ELT(nms, 28, mkChar("M_T_ini"));
  SET_STRING_ELT(nms, 29, mkChar("n"));
  SET_STRING_ELT(nms, 30, mkChar("P_0_ini"));
  SET_STRING_ELT(nms, 31, mkChar("P_1_ini"));
  SET_STRING_ELT(nms, 32, mkChar("P_2_ini"));
  SET_STRING_ELT(nms, 33, mkChar("STEP_HOURS"));
  SET_STRING_ELT(nms, 34, mkChar("T_0_ini"));
  SET_STRING_ELT(nms, 35, mkChar("T_1_ini"));
  SET_STRING_ELT(nms, 36, mkChar("T_2_ini"));
  SET_STRING_ELT(nms, 37, mkChar("V_1P"));
  SET_STRING_ELT(nms, 38, mkChar("V_1T"));
  SET_STRING_ELT(nms, 39, mkChar("V_2P"));
  SET_STRING_ELT(nms, 40, mkChar("V_2T"));
  SET_STRING_ELT(nms, 41, mkChar("V_3P"));
  SET_STRING_ELT(nms, 42, mkChar("V_3T"));
  SET_STRING_ELT(nms, 43, mkChar("V_4P"));
  SET_STRING_ELT(nms, 44, mkChar("V_4T"));
  SET_STRING_ELT(nms, 45, mkChar("V_dP"));
  SET_STRING_ELT(nms, 46, mkChar("V_mP"));
  SET_STRING_ELT(nms, 47, mkChar("V_mT"));
  SET_STRING_ELT(nms, 48, mkChar("V_sP"));
  SET_STRING_ELT(nms, 49, mkChar("V_sT"));
  SET_STRING_ELT(nms, 50, mkChar("VdT_OFF"));
  SET_STRING_ELT(nms, 51, mkChar("VdT_ON"));
  setAttrib(contents, R_NamesSymbol, nms);
  UNPROTECT(2);
  return contents;
}
SEXP discrete_leloup_goldbeter_set_user(SEXP internal_p, SEXP user) {
  discrete_leloup_goldbeter_internal *internal = discrete_leloup_goldbeter_get_internal(internal_p, 1);
  internal->C_ini = user_get_scalar_double(user, "C_ini", internal->C_ini, NA_REAL, NA_REAL);
  internal->C_N_ini = user_get_scalar_double(user, "C_N_ini", internal->C_N_ini, NA_REAL, NA_REAL);
  internal->k_1 = user_get_scalar_double(user, "k_1", internal->k_1, NA_REAL, NA_REAL);
  internal->k_2 = user_get_scalar_double(user, "k_2", internal->k_2, NA_REAL, NA_REAL);
  internal->k_3 = user_get_scalar_double(user, "k_3", internal->k_3, NA_REAL, NA_REAL);
  internal->k_4 = user_get_scalar_double(user, "k_4", internal->k_4, NA_REAL, NA_REAL);
  internal->k_d = user_get_scalar_double(user, "k_d", internal->k_d, NA_REAL, NA_REAL);
  internal->K_dP = user_get_scalar_double(user, "K_dP", internal->K_dP, NA_REAL, NA_REAL);
  internal->K_dT = user_get_scalar_double(user, "K_dT", internal->K_dT, NA_REAL, NA_REAL);
  internal->K_IP = user_get_scalar_double(user, "K_IP", internal->K_IP, NA_REAL, NA_REAL);
  internal->K_IT = user_get_scalar_double(user, "K_IT", internal->K_IT, NA_REAL, NA_REAL);
  internal->K_mP = user_get_scalar_double(user, "K_mP", internal->K_mP, NA_REAL, NA_REAL);
  internal->K_mT = user_get_scalar_double(user, "K_mT", internal->K_mT, NA_REAL, NA_REAL);
  internal->K_p = user_get_scalar_double(user, "K_p", internal->K_p, NA_REAL, NA_REAL);
  internal->k_sP = user_get_scalar_double(user, "k_sP", internal->k_sP, NA_REAL, NA_REAL);
  internal->k_sT = user_get_scalar_double(user, "k_sT", internal->k_sT, NA_REAL, NA_REAL);
  internal->LD_HOURS = user_get_scalar_double(user, "LD_HOURS", internal->LD_HOURS, NA_REAL, NA_REAL);
  internal->M_P_ini = user_get_scalar_double(user, "M_P_ini", internal->M_P_ini, NA_REAL, NA_REAL);
  internal->M_T_ini = user_get_scalar_double(user, "M_T_ini", internal->M_T_ini, NA_REAL, NA_REAL);
  internal->n = user_get_scalar_double(user, "n", internal->n, NA_REAL, NA_REAL);
  internal->P_0_ini = user_get_scalar_double(user, "P_0_ini", internal->P_0_ini, NA_REAL, NA_REAL);
  internal->P_1_ini = user_get_scalar_double(user, "P_1_ini", internal->P_1_ini, NA_REAL, NA_REAL);
  internal->P_2_ini = user_get_scalar_double(user, "P_2_ini", internal->P_2_ini, NA_REAL, NA_REAL);
  internal->STEP_HOURS = user_get_scalar_double(user, "STEP_HOURS", internal->STEP_HOURS, NA_REAL, NA_REAL);
  internal->T_0_ini = user_get_scalar_double(user, "T_0_ini", internal->T_0_ini, NA_REAL, NA_REAL);
  internal->T_1_ini = user_get_scalar_double(user, "T_1_ini", internal->T_1_ini, NA_REAL, NA_REAL);
  internal->T_2_ini = user_get_scalar_double(user, "T_2_ini", internal->T_2_ini, NA_REAL, NA_REAL);
  internal->V_1P = user_get_scalar_double(user, "V_1P", internal->V_1P, NA_REAL, NA_REAL);
  internal->V_1T = user_get_scalar_double(user, "V_1T", internal->V_1T, NA_REAL, NA_REAL);
  internal->V_2P = user_get_scalar_double(user, "V_2P", internal->V_2P, NA_REAL, NA_REAL);
  internal->V_2T = user_get_scalar_double(user, "V_2T", internal->V_2T, NA_REAL, NA_REAL);
  internal->V_3P = user_get_scalar_double(user, "V_3P", internal->V_3P, NA_REAL, NA_REAL);
  internal->V_3T = user_get_scalar_double(user, "V_3T", internal->V_3T, NA_REAL, NA_REAL);
  internal->V_4P = user_get_scalar_double(user, "V_4P", internal->V_4P, NA_REAL, NA_REAL);
  internal->V_4T = user_get_scalar_double(user, "V_4T", internal->V_4T, NA_REAL, NA_REAL);
  internal->V_dP = user_get_scalar_double(user, "V_dP", internal->V_dP, NA_REAL, NA_REAL);
  internal->V_mP = user_get_scalar_double(user, "V_mP", internal->V_mP, NA_REAL, NA_REAL);
  internal->V_mT = user_get_scalar_double(user, "V_mT", internal->V_mT, NA_REAL, NA_REAL);
  internal->V_sP = user_get_scalar_double(user, "V_sP", internal->V_sP, NA_REAL, NA_REAL);
  internal->V_sT = user_get_scalar_double(user, "V_sT", internal->V_sT, NA_REAL, NA_REAL);
  internal->VdT_OFF = user_get_scalar_double(user, "VdT_OFF", internal->VdT_OFF, NA_REAL, NA_REAL);
  internal->VdT_ON = user_get_scalar_double(user, "VdT_ON", internal->VdT_ON, NA_REAL, NA_REAL);
  internal->initial_C = internal->C_ini;
  internal->initial_C_N = internal->C_N_ini;
  internal->initial_M_P = internal->M_P_ini;
  internal->initial_M_T = internal->M_T_ini;
  internal->initial_P_0 = internal->P_0_ini;
  internal->initial_P_1 = internal->P_1_ini;
  internal->initial_P_2 = internal->P_2_ini;
  internal->initial_T_0 = internal->T_0_ini;
  internal->initial_T_1 = internal->T_1_ini;
  internal->initial_T_2 = internal->T_2_ini;
  return R_NilValue;
}
SEXP discrete_leloup_goldbeter_set_initial(SEXP internal_p, SEXP step_ptr, SEXP state_ptr) {
  return R_NilValue;
}
SEXP discrete_leloup_goldbeter_metadata(SEXP internal_p) {
  discrete_leloup_goldbeter_internal *internal = discrete_leloup_goldbeter_get_internal(internal_p, 1);
  SEXP ret = PROTECT(allocVector(VECSXP, 4));
  SEXP nms = PROTECT(allocVector(STRSXP, 4));
  SET_STRING_ELT(nms, 0, mkChar("variable_order"));
  SET_STRING_ELT(nms, 1, mkChar("output_order"));
  SET_STRING_ELT(nms, 2, mkChar("n_out"));
  SET_STRING_ELT(nms, 3, mkChar("interpolate_t"));
  setAttrib(ret, R_NamesSymbol, nms);
  SEXP variable_length = PROTECT(allocVector(VECSXP, 10));
  SEXP variable_names = PROTECT(allocVector(STRSXP, 10));
  setAttrib(variable_length, R_NamesSymbol, variable_names);
  SET_VECTOR_ELT(variable_length, 0, R_NilValue);
  SET_VECTOR_ELT(variable_length, 1, R_NilValue);
  SET_VECTOR_ELT(variable_length, 2, R_NilValue);
  SET_VECTOR_ELT(variable_length, 3, R_NilValue);
  SET_VECTOR_ELT(variable_length, 4, R_NilValue);
  SET_VECTOR_ELT(variable_length, 5, R_NilValue);
  SET_VECTOR_ELT(variable_length, 6, R_NilValue);
  SET_VECTOR_ELT(variable_length, 7, R_NilValue);
  SET_VECTOR_ELT(variable_length, 8, R_NilValue);
  SET_VECTOR_ELT(variable_length, 9, R_NilValue);
  SET_STRING_ELT(variable_names, 0, mkChar("M_T"));
  SET_STRING_ELT(variable_names, 1, mkChar("M_P"));
  SET_STRING_ELT(variable_names, 2, mkChar("T_0"));
  SET_STRING_ELT(variable_names, 3, mkChar("T_1"));
  SET_STRING_ELT(variable_names, 4, mkChar("T_2"));
  SET_STRING_ELT(variable_names, 5, mkChar("P_0"));
  SET_STRING_ELT(variable_names, 6, mkChar("P_1"));
  SET_STRING_ELT(variable_names, 7, mkChar("P_2"));
  SET_STRING_ELT(variable_names, 8, mkChar("C"));
  SET_STRING_ELT(variable_names, 9, mkChar("C_N"));
  SET_VECTOR_ELT(ret, 0, variable_length);
  UNPROTECT(2);
  SET_VECTOR_ELT(ret, 1, R_NilValue);
  SET_VECTOR_ELT(ret, 2, ScalarInteger(0));
  UNPROTECT(2);
  return ret;
}
SEXP discrete_leloup_goldbeter_initial_conditions(SEXP internal_p, SEXP step_ptr) {
  discrete_leloup_goldbeter_internal *internal = discrete_leloup_goldbeter_get_internal(internal_p, 1);
  SEXP r_state = PROTECT(allocVector(REALSXP, 10));
  double * state = REAL(r_state);
  state[0] = internal->initial_M_T;
  state[1] = internal->initial_M_P;
  state[2] = internal->initial_T_0;
  state[3] = internal->initial_T_1;
  state[4] = internal->initial_T_2;
  state[5] = internal->initial_P_0;
  state[6] = internal->initial_P_1;
  state[7] = internal->initial_P_2;
  state[8] = internal->initial_C;
  state[9] = internal->initial_C_N;
  UNPROTECT(1);
  return r_state;
}
void discrete_leloup_goldbeter_rhs(discrete_leloup_goldbeter_internal* internal, size_t step, double * state, double * state_next, double * output) {
  double M_T = state[0];
  double M_P = state[1];
  double T_0 = state[2];
  double T_1 = state[3];
  double T_2 = state[4];
  double P_0 = state[5];
  double P_1 = state[6];
  double P_2 = state[7];
  double C = state[8];
  double C_N = state[9];
  double current_hour = step * internal->STEP_HOURS;
  double inc_hour1 = internal->V_sT * pow(internal->K_IT, internal->n) / (double) (pow(internal->K_IT, internal->n) + pow(C_N, internal->n)) - internal->k_d * M_T - internal->V_mT * M_T / (double) (internal->K_mT + M_T);
  double inc_hour10 = internal->k_1 * C - internal->k_2 * C_N - internal->k_d * C_N;
  double inc_hour2 = internal->V_sP * pow(internal->K_IP, internal->n) / (double) (pow(internal->K_IP, internal->n) + pow(C_N, internal->n)) - internal->k_d * M_P - internal->V_mP * M_P / (double) (internal->K_mP + M_P);
  double inc_hour3 = internal->k_sT * M_T + internal->V_2T * T_1 / (double) (internal->K_p + T_1) - internal->k_d * T_0 - internal->V_1T * T_0 / (double) (internal->K_p + T_0);
  double inc_hour4 = internal->V_1T * T_0 / (double) (internal->K_p + T_0) + internal->V_4T * T_2 / (double) (internal->K_p + T_2) - internal->k_d * T_1 - internal->V_2T * T_1 / (double) (internal->K_p + T_1) - internal->V_3T * T_1 / (double) (internal->K_p + T_1);
  double inc_hour6 = internal->k_sP * M_P + internal->V_2P * P_1 / (double) (internal->K_p + P_1) - internal->k_d * P_0 - internal->V_1P * P_0 / (double) (internal->K_p + P_0);
  double inc_hour7 = internal->V_1P * P_0 / (double) (internal->K_p + P_0) + internal->V_4P * P_2 / (double) (internal->K_p + P_2) - internal->k_d * P_1 - internal->V_2P * P_1 / (double) (internal->K_p + P_1) - internal->V_3P * P_1 / (double) (internal->K_p + P_1);
  double inc_hour8 = internal->V_3P * P_1 / (double) (internal->K_p + P_1) + internal->k_4 * C - internal->k_d * P_2 - internal->k_3 * P_2 * P_2 - internal->V_4P * P_2 / (double) (internal->K_p + P_2) - internal->V_dP * P_2 / (double) (internal->K_dP + P_2);
  double inc_hour9 = internal->k_3 * P_2 * T_2 + internal->k_2 * C_N - (internal->k_4 * C + internal->k_1 * C + internal->k_d * C);
  state_next[8] = C + inc_hour9 * internal->STEP_HOURS;
  state_next[9] = C_N + inc_hour10 * internal->STEP_HOURS;
  state_next[1] = M_P + inc_hour2 * internal->STEP_HOURS;
  state_next[0] = M_T + inc_hour1 * internal->STEP_HOURS;
  state_next[5] = P_0 + inc_hour6 * internal->STEP_HOURS;
  state_next[6] = P_1 + inc_hour7 * internal->STEP_HOURS;
  state_next[7] = P_2 + inc_hour8 * internal->STEP_HOURS;
  state_next[2] = T_0 + inc_hour3 * internal->STEP_HOURS;
  state_next[3] = T_1 + inc_hour4 * internal->STEP_HOURS;
  double V_dT = (current_hour <= internal->LD_HOURS && (fmodr((fintdiv(current_hour, 12)), 2) == 1) ? internal->VdT_ON : internal->VdT_OFF);
  double inc_hour5 = internal->V_3T * T_1 / (double) (internal->K_p + T_1) + internal->k_4 * C - internal->k_d * T_2 - internal->k_3 * P_2 * T_2 - internal->V_4T * T_2 / (double) (internal->K_p + T_2) - V_dT * T_2 / (double) (internal->K_dT + T_2);
  state_next[4] = T_2 + inc_hour5 * internal->STEP_HOURS;
}
void discrete_leloup_goldbeter_rhs_dde(size_t n_eq, size_t step, double * state, double * state_next, size_t n_out, double * output, void * internal) {
  discrete_leloup_goldbeter_rhs((discrete_leloup_goldbeter_internal*)internal, step, state, state_next, output);
}
SEXP discrete_leloup_goldbeter_rhs_r(SEXP internal_p, SEXP step, SEXP state) {
  SEXP state_next = PROTECT(allocVector(REALSXP, LENGTH(state)));
  discrete_leloup_goldbeter_internal *internal = discrete_leloup_goldbeter_get_internal(internal_p, 1);
  double *output = NULL;
  discrete_leloup_goldbeter_rhs(internal, scalar_int(step, "step"), REAL(state), REAL(state_next), output);
  UNPROTECT(1);
  return state_next;
}
double user_get_scalar_double(SEXP user, const char *name,
                              double default_value, double min, double max) {
  double ret = default_value;
  SEXP el = user_list_element(user, name);
  if (el != R_NilValue) {
    if (length(el) != 1) {
      Rf_error("Expected a scalar numeric for '%s'", name);
    }
    if (TYPEOF(el) == REALSXP) {
      ret = REAL(el)[0];
    } else if (TYPEOF(el) == INTSXP) {
      ret = INTEGER(el)[0];
    } else {
      Rf_error("Expected a numeric value for '%s'", name);
    }
  }
  if (ISNA(ret)) {
    Rf_error("Expected a value for '%s'", name);
  }
  user_check_values_double(&ret, 1, min, max, name);
  return ret;
}
int user_get_scalar_int(SEXP user, const char *name,
                        int default_value, double min, double max) {
  int ret = default_value;
  SEXP el = user_list_element(user, name);
  if (el != R_NilValue) {
    if (length(el) != 1) {
      Rf_error("Expected scalar integer for '%s'", name);
    }
    if (TYPEOF(el) == REALSXP) {
      double tmp = REAL(el)[0];
      if (fabs(tmp - round(tmp)) > 2e-8) {
        Rf_error("Expected '%s' to be integer-like", name);
      }
    }
    ret = INTEGER(coerceVector(el, INTSXP))[0];
  }
  if (ret == NA_INTEGER) {
    Rf_error("Expected a value for '%s'", name);
  }
  user_check_values_int(&ret, 1, min, max, name);
  return ret;
}
void user_check_values_double(double * value, size_t len,
                                  double min, double max, const char *name) {
  for (size_t i = 0; i < len; ++i) {
    if (ISNA(value[i])) {
      Rf_error("'%s' must not contain any NA values", name);
    }
  }
  if (min != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] < min) {
        Rf_error("Expected '%s' to be at least %g", name, min);
      }
    }
  }
  if (max != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] > max) {
        Rf_error("Expected '%s' to be at most %g", name, max);
      }
    }
  }
}
void user_check_values_int(int * value, size_t len,
                               double min, double max, const char *name) {
  for (size_t i = 0; i < len; ++i) {
    if (ISNA(value[i])) {
      Rf_error("'%s' must not contain any NA values", name);
    }
  }
  if (min != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] < min) {
        Rf_error("Expected '%s' to be at least %g", name, min);
      }
    }
  }
  if (max != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] > max) {
        Rf_error("Expected '%s' to be at most %g", name, max);
      }
    }
  }
}
void user_check_values(SEXP value, double min, double max,
                           const char *name) {
  size_t len = (size_t)length(value);
  if (TYPEOF(value) == INTSXP) {
    user_check_values_int(INTEGER(value), len, min, max, name);
  } else {
    user_check_values_double(REAL(value), len, min, max, name);
  }
}
SEXP user_list_element(SEXP list, const char *name) {
  SEXP ret = R_NilValue, names = getAttrib(list, R_NamesSymbol);
  for (int i = 0; i < length(list); ++i) {
    if (strcmp(CHAR(STRING_ELT(names, i)), name) == 0) {
      ret = VECTOR_ELT(list, i);
      break;
    }
  }
  return ret;
}
double fmodr(double x, double y) {
  double tmp = fmod(x, y);
  if (tmp * y < 0) {
    tmp += y;
  }
  return tmp;
}
double fintdiv(double x, double y) {
  return floor(x / y);
}
int scalar_int(SEXP x, const char * name) {
  if (Rf_length(x) != 1) {
    Rf_error("Expected a scalar for '%s'", name);
  }
  int ret = 0;
  if (TYPEOF(x) == INTSXP) {
    ret = INTEGER(x)[0];
  } else if (TYPEOF(x) == REALSXP) {
    double rx = REAL(x)[0];
    ret = rx;
    if (fabs(rx - ret) > sqrt(DBL_EPSILON)) {
      Rf_error("Expected a integer-like for '%s'", name);
    }
  } else {
    Rf_error("Expected an integer value for '%s'", name);
  }
  return ret;
}
