## Automatically generated by odin 1.2.7 - do not edit
discrete_leloup_goldbeter_noisy_ <- R6::R6Class(
  "odin_model",
  cloneable = FALSE,

  private = list(
    ptr = NULL,
    use_dde = NULL,

    odin = NULL,
    variable_order = NULL,
    output_order = NULL,
    n_out = NULL,
    ynames = NULL,
    interpolate_t = NULL,
    cfuns = list(
      rhs_dde = "discrete_leloup_goldbeter_noisy_rhs_dde"),
    dll = "clockSim",
    user = c("C_ini", "C_N_ini", "k_1", "k_2", "k_3", "k_4", "k_d", "K_dP",
             "K_dT", "K_IP", "K_IT", "K_mP", "K_mT", "K_p", "k_sP", "k_sT",
             "LD_HOURS", "M_P_ini", "M_T_ini", "n", "P_0_ini", "P_1_ini",
             "P_2_ini", "STEP_HOURS", "T_0_ini", "T_1_ini", "T_2_ini",
             "V_1P", "V_1T", "V_2P", "V_2T", "V_3P", "V_3T", "V_4P", "V_4T",
             "V_dP", "V_mP", "V_mT", "V_sP", "V_sT", "VdT_OFF", "VdT_ON",
             "VsP_NOISE_RATIO", "VsP_NOISE_TYPE", "VsT_NOISE_RATIO",
             "VsT_NOISE_TYPE"),

    ## This is never called, but is used to ensure that R finds our
    ## symbols that we will use from the package; without this they
    ## cannot be found by dynamic lookup now that we use the package
    ## FFI registration system.
    registration = function() {
      if (FALSE) {
        .C("discrete_leloup_goldbeter_noisy_rhs_dde", package = "clockSim")
      }
    },

    ## This only does something in delay models
    set_initial = function(step, y, use_dde) {
      .Call("discrete_leloup_goldbeter_noisy_set_initial", private$ptr, step, y, use_dde,
            PACKAGE= "clockSim")
    },

    update_metadata = function() {
      meta <- .Call("discrete_leloup_goldbeter_noisy_metadata", private$ptr,
                    PACKAGE = "clockSim")
      private$variable_order <- meta$variable_order
      private$output_order <- meta$output_order
      private$n_out <- meta$n_out
      private$ynames <- private$odin$make_names(
        private$variable_order, private$output_order, TRUE)
      private$interpolate_t <- meta$interpolate_t
    }
  ),

  public = list(
    initialize = function(..., user = list(...), use_dde = FALSE,
                          unused_user_action = NULL) {
      private$odin <- asNamespace("odin")
      private$ptr <- .Call("discrete_leloup_goldbeter_noisy_create", user, PACKAGE = "clockSim")
      self$set_user(user = user, unused_user_action = unused_user_action)
      private$use_dde <- use_dde
      private$update_metadata()
    },

    ir = function() {
      path_ir <- system.file("odin/discrete_leloup_goldbeter_noisy.json", mustWork = TRUE,
                             package = "clockSim")
      json <- readLines(path_ir)
      class(json) <- "json"
      json
    },

    ## Do we need to have the user-settable args here? It would be
    ## nice, but that's not super straightforward to do.
    set_user = function(..., user = list(...), unused_user_action = NULL) {
      private$odin$support_check_user(user, private$user, unused_user_action)
      .Call("discrete_leloup_goldbeter_noisy_set_user", private$ptr, user, PACKAGE = "clockSim")
      private$update_metadata()
    },

    ## This might be time sensitive and, so we can avoid computing
    ## it. I wonder if that's an optimisation we should drop for now
    ## as it does not seem generally useful. This would bring us
    ## closer to the js version which requires that we always pass the
    ## time in.
    initial = function(step) {
      .Call("discrete_leloup_goldbeter_noisy_initial_conditions", private$ptr, step, PACKAGE = "clockSim")
    },

    rhs = function(step, y) {
      .Call("discrete_leloup_goldbeter_noisy_rhs_r", private$ptr, step, y, PACKAGE = "clockSim")
    },

    update = function(step, y) {
      self$rhs(step, y)
    },

    contents = function() {
      .Call("discrete_leloup_goldbeter_noisy_contents", private$ptr, PACKAGE = "clockSim")
    },

    transform_variables = function(y) {
      private$odin$support_transform_variables(y, private)
    },

    run = function(step, y = NULL, ..., use_names = TRUE) {
      private$odin$wrapper_run_discrete(
        self, private, step, y, ..., use_names = use_names)
    }
  ))


discrete_leloup_goldbeter_noisy <- function(..., user = list(...), use_dde = FALSE,
                     unused_user_action = NULL) {
  asNamespace("odin")$deprecated_constructor_call("discrete_leloup_goldbeter_noisy")
  discrete_leloup_goldbeter_noisy_$new(user = user, use_dde = use_dde,
                unused_user_action = unused_user_action)
}
class(discrete_leloup_goldbeter_noisy) <- "odin_generator"
attr(discrete_leloup_goldbeter_noisy, "generator") <- discrete_leloup_goldbeter_noisy_
discrete_leloup_goldbeter_ <- R6::R6Class(
  "odin_model",
  cloneable = FALSE,

  private = list(
    ptr = NULL,
    use_dde = NULL,

    odin = NULL,
    variable_order = NULL,
    output_order = NULL,
    n_out = NULL,
    ynames = NULL,
    interpolate_t = NULL,
    cfuns = list(
      rhs_dde = "discrete_leloup_goldbeter_rhs_dde"),
    dll = "clockSim",
    user = c("C_ini", "C_N_ini", "k_1", "k_2", "k_3", "k_4", "k_d", "K_dP",
             "K_dT", "K_IP", "K_IT", "K_mP", "K_mT", "K_p", "k_sP", "k_sT",
             "LD_HOURS", "M_P_ini", "M_T_ini", "n", "P_0_ini", "P_1_ini",
             "P_2_ini", "STEP_HOURS", "T_0_ini", "T_1_ini", "T_2_ini",
             "V_1P", "V_1T", "V_2P", "V_2T", "V_3P", "V_3T", "V_4P", "V_4T",
             "V_dP", "V_mP", "V_mT", "V_sP", "V_sT", "VdT_OFF", "VdT_ON"),

    ## This is never called, but is used to ensure that R finds our
    ## symbols that we will use from the package; without this they
    ## cannot be found by dynamic lookup now that we use the package
    ## FFI registration system.
    registration = function() {
      if (FALSE) {
        .C("discrete_leloup_goldbeter_rhs_dde", package = "clockSim")
      }
    },

    ## This only does something in delay models
    set_initial = function(step, y, use_dde) {
      .Call("discrete_leloup_goldbeter_set_initial", private$ptr, step, y, use_dde,
            PACKAGE= "clockSim")
    },

    update_metadata = function() {
      meta <- .Call("discrete_leloup_goldbeter_metadata", private$ptr,
                    PACKAGE = "clockSim")
      private$variable_order <- meta$variable_order
      private$output_order <- meta$output_order
      private$n_out <- meta$n_out
      private$ynames <- private$odin$make_names(
        private$variable_order, private$output_order, TRUE)
      private$interpolate_t <- meta$interpolate_t
    }
  ),

  public = list(
    initialize = function(..., user = list(...), use_dde = FALSE,
                          unused_user_action = NULL) {
      private$odin <- asNamespace("odin")
      private$ptr <- .Call("discrete_leloup_goldbeter_create", user, PACKAGE = "clockSim")
      self$set_user(user = user, unused_user_action = unused_user_action)
      private$use_dde <- use_dde
      private$update_metadata()
    },

    ir = function() {
      path_ir <- system.file("odin/discrete_leloup_goldbeter.json", mustWork = TRUE,
                             package = "clockSim")
      json <- readLines(path_ir)
      class(json) <- "json"
      json
    },

    ## Do we need to have the user-settable args here? It would be
    ## nice, but that's not super straightforward to do.
    set_user = function(..., user = list(...), unused_user_action = NULL) {
      private$odin$support_check_user(user, private$user, unused_user_action)
      .Call("discrete_leloup_goldbeter_set_user", private$ptr, user, PACKAGE = "clockSim")
      private$update_metadata()
    },

    ## This might be time sensitive and, so we can avoid computing
    ## it. I wonder if that's an optimisation we should drop for now
    ## as it does not seem generally useful. This would bring us
    ## closer to the js version which requires that we always pass the
    ## time in.
    initial = function(step) {
      .Call("discrete_leloup_goldbeter_initial_conditions", private$ptr, step, PACKAGE = "clockSim")
    },

    rhs = function(step, y) {
      .Call("discrete_leloup_goldbeter_rhs_r", private$ptr, step, y, PACKAGE = "clockSim")
    },

    update = function(step, y) {
      self$rhs(step, y)
    },

    contents = function() {
      .Call("discrete_leloup_goldbeter_contents", private$ptr, PACKAGE = "clockSim")
    },

    transform_variables = function(y) {
      private$odin$support_transform_variables(y, private)
    },

    run = function(step, y = NULL, ..., use_names = TRUE) {
      private$odin$wrapper_run_discrete(
        self, private, step, y, ..., use_names = use_names)
    }
  ))


discrete_leloup_goldbeter <- function(..., user = list(...), use_dde = FALSE,
                     unused_user_action = NULL) {
  asNamespace("odin")$deprecated_constructor_call("discrete_leloup_goldbeter")
  discrete_leloup_goldbeter_$new(user = user, use_dde = use_dde,
                unused_user_action = unused_user_action)
}
class(discrete_leloup_goldbeter) <- "odin_generator"
attr(discrete_leloup_goldbeter, "generator") <- discrete_leloup_goldbeter_
